#!/usr/bin/env bash

set -e

FILENAME=${1:-README.md}

modules="ansi-to-html markdown-toc"

for module in $modules ; do
  if ! which $module ; then
    echo "NOTICE: installing npm module $module ..."
    npm install --global $module
  fi
done

echo "Generating content into ${FILENAME} ..."
export THOR_COLUMNS=100
erb README.md.erb > $FILENAME
markdown-toc $FILENAME -i --maxdepth 3
