name: Test suite

on:
  workflow_dispatch: {}
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]
    branches: [master]
  schedule:
    - cron: "0 8 * * 5" # At 08:00 on Friday, an hour after the test image is generated. https://crontab.guru/#0_8_*_*_5

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.6", "2.7", "3.0", "3.1"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - name: Run test suite
        run: ./ci/run.sh
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
